// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Standalone test page for GCode preview.
 * Access via: http://localhost:5173/test-gcode-preview.html
 *
 * Uses hardcoded GCode samples to test the preview component
 * without requiring a slicer engine.
 */
import { createRoot } from 'react-dom/client';
import { useState, useEffect } from 'react';
import { parseGCode } from './lib/gcode-parser';
import type { ParsedGCode } from './lib/gcode-parser';
import { GCodePreview } from './components/GCodePreview';
import './app.css';

// ============================================================
// Hardcoded GCode samples
// ============================================================

/** Small 20x20x2mm cube — 10 layers at 0.2mm layer height */
const CUBE_GCODE = `; generated by test-gcode-preview
; Simple cube for GCode preview testing
M140 S60
M104 S210
M190 S60
M109 S210
G28
G92 E0
M83
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;TYPE:Skirt
G1 Z0.2 F3000
G1 X100 Y100 F6000
G1 X120 Y100 E0.5 F1200
G1 X120 Y120 E0.5
G1 X100 Y120 E0.5
G1 X100 Y100 E0.5
;TYPE:External perimeter
G1 X105 Y105 F6000
G1 X115 Y105 E0.25 F1200
G1 X115 Y115 E0.25
G1 X105 Y115 E0.25
G1 X105 Y105 E0.25
;TYPE:Perimeter
G1 X104 Y104 F6000
G1 X116 Y104 E0.3 F1200
G1 X116 Y116 E0.3
G1 X104 Y116 E0.3
G1 X104 Y104 E0.3
;TYPE:Solid infill
G1 X105 Y106 F6000
G1 X115 Y106 E0.25 F1200
G1 X115 Y108 F6000
G1 X105 Y108 E0.25 F1200
G1 X105 Y110 F6000
G1 X115 Y110 E0.25 F1200
G1 X115 Y112 F6000
G1 X105 Y112 E0.25 F1200
G1 X105 Y114 F6000
G1 X115 Y114 E0.25 F1200
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;TYPE:External perimeter
G1 Z0.4 F3000
G1 X105 Y105 F6000
G1 X115 Y105 E0.25 F1200
G1 X115 Y115 E0.25
G1 X105 Y115 E0.25
G1 X105 Y105 E0.25
;TYPE:Internal infill
G1 X106 Y105 F6000
G1 X106 Y115 E0.25 F1200
G1 X108 Y115 F6000
G1 X108 Y105 E0.25 F1200
G1 X110 Y105 F6000
G1 X110 Y115 E0.25 F1200
G1 X112 Y115 F6000
G1 X112 Y105 E0.25 F1200
G1 X114 Y105 F6000
G1 X114 Y115 E0.25 F1200
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;TYPE:External perimeter
G1 Z0.6 F3000
G1 X105 Y105 F6000
G1 X115 Y105 E0.25 F1200
G1 X115 Y115 E0.25
G1 X105 Y115 E0.25
G1 X105 Y105 E0.25
;TYPE:Internal infill
G1 X105 Y106 F6000
G1 X115 Y106 E0.25 F1200
G1 X115 Y108 F6000
G1 X105 Y108 E0.25 F1200
G1 X105 Y110 F6000
G1 X115 Y110 E0.25 F1200
G1 X115 Y112 F6000
G1 X105 Y112 E0.25 F1200
G1 X105 Y114 F6000
G1 X115 Y114 E0.25 F1200
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;TYPE:External perimeter
G1 Z0.8 F3000
G1 X105 Y105 F6000
G1 X115 Y105 E0.25 F1200
G1 X115 Y115 E0.25
G1 X105 Y115 E0.25
G1 X105 Y105 E0.25
;TYPE:Internal infill
G1 X106 Y105 F6000
G1 X106 Y115 E0.25 F1200
G1 X108 Y115 F6000
G1 X108 Y105 E0.25 F1200
G1 X110 Y105 F6000
G1 X110 Y115 E0.25 F1200
G1 X112 Y115 F6000
G1 X112 Y105 E0.25 F1200
G1 X114 Y105 F6000
G1 X114 Y115 E0.25 F1200
;LAYER_CHANGE
;Z:1.0
;HEIGHT:0.2
;TYPE:External perimeter
G1 Z1.0 F3000
G1 X105 Y105 F6000
G1 X115 Y105 E0.25 F1200
G1 X115 Y115 E0.25
G1 X105 Y115 E0.25
G1 X105 Y105 E0.25
;TYPE:Top solid infill
G1 X105 Y106 F6000
G1 X115 Y106 E0.25 F1200
G1 X115 Y108 F6000
G1 X105 Y108 E0.25 F1200
G1 X105 Y110 F6000
G1 X115 Y110 E0.25 F1200
G1 X115 Y112 F6000
G1 X105 Y112 E0.25 F1200
G1 X105 Y114 F6000
G1 X115 Y114 E0.25 F1200
M104 S0
M140 S0
G28 X Y
M84
; filament used [mm] = 123.4
; estimated printing time (normal mode) = 0h 2m 30s
`;

/** Two-extruder GCode (simplified multi-color) */
const MULTICOLOR_GCODE = `; generated by test-gcode-preview
; Multi-color test: two extruders
M140 S60
M104 S210
M190 S60
M109 S210
G28
G92 E0
M83
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
T0
;TYPE:External perimeter
G1 Z0.2 F3000
G1 X100 Y100 F6000
G1 X110 Y100 E0.25 F1200
G1 X110 Y110 E0.25
G1 X100 Y110 E0.25
G1 X100 Y100 E0.25
;TYPE:Solid infill
G1 X101 Y102 F6000
G1 X109 Y102 E0.2 F1200
G1 X109 Y104 F6000
G1 X101 Y104 E0.2 F1200
G1 X101 Y106 F6000
G1 X109 Y106 E0.2 F1200
G1 X109 Y108 F6000
G1 X101 Y108 E0.2 F1200
;TYPE:Wipe tower
G1 X130 Y100 F6000
G1 X140 Y100 E0.25 F1200
G1 X140 Y110 E0.25
G1 X130 Y110 E0.25
G1 X130 Y100 E0.25
T1
;TYPE:External perimeter
G1 X112 Y100 F6000
G1 X122 Y100 E0.25 F1200
G1 X122 Y110 E0.25
G1 X112 Y110 E0.25
G1 X112 Y100 E0.25
;TYPE:Solid infill
G1 X113 Y102 F6000
G1 X121 Y102 E0.2 F1200
G1 X121 Y104 F6000
G1 X113 Y104 E0.2 F1200
G1 X113 Y106 F6000
G1 X121 Y106 E0.2 F1200
G1 X121 Y108 F6000
G1 X113 Y108 E0.2 F1200
M104 S0
M140 S0
G28 X Y
M84
; filament used [mm] = 45.6
; estimated printing time (normal mode) = 0h 1m 15s
`;

interface Example {
  id: string;
  label: string;
  gcode: string;
  extruderColors?: string[];
}

const EXAMPLES: Example[] = [
  {
    id: 'cube',
    label: 'Cube (5 layers)',
    gcode: CUBE_GCODE,
  },
  {
    id: 'multicolor',
    label: 'Multi-Color (2 extruders)',
    gcode: MULTICOLOR_GCODE,
    extruderColors: ['#e74c3c', '#3498db'],
  },
];

const PRINTER = {
  bedWidth: 235,
  bedDepth: 235,
  originCenter: false,
};

// ============================================================
// Main component
// ============================================================

function TestApp() {
  const [parsedGCode, setParsedGCode] = useState<ParsedGCode | null>(null);
  const [activeTab, setActiveTab] = useState(EXAMPLES[0].id);
  const [status, setStatus] = useState('');
  const [extruderColors, setExtruderColors] = useState<string[] | undefined>(undefined);

  function loadExample(example: Example) {
    setExtruderColors(example.extruderColors);
    const parsed = parseGCode(example.gcode);
    setParsedGCode(parsed);
    setStatus(`${parsed.layers.length} layers, ${parsed.totalSegments} segments`);
  }

  useEffect(() => {
    const example = EXAMPLES.find(e => e.id === activeTab);
    if (example) loadExample(example);
  }, []);

  return (
    <div style={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Tab bar */}
      <div style={{
        padding: '8px 16px',
        background: '#2a2a4e',
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        flexShrink: 0,
        zIndex: 10,
      }}>
        <span style={{ fontSize: '14px', opacity: 0.7 }}>{status}</span>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: '8px', flexShrink: 0 }}>
          {EXAMPLES.map(ex => (
            <button
              key={ex.id}
              onClick={() => {
                setActiveTab(ex.id);
                loadExample(ex);
              }}
              style={{
                padding: '4px 12px',
                background: activeTab === ex.id ? '#4a90d9' : '#444',
                color: '#fff',
                border: 'none',
                borderRadius: '4px',
                cursor: 'pointer',
                fontSize: '13px',
                whiteSpace: 'nowrap',
              }}
            >
              {ex.label}
            </button>
          ))}
        </div>
      </div>

      {/* GCode preview */}
      <div style={{ flex: 1, position: 'relative' }}>
        {parsedGCode && (
          <GCodePreview
            parsedGCode={parsedGCode}
            bedWidth={PRINTER.bedWidth}
            bedDepth={PRINTER.bedDepth}
            originCenter={PRINTER.originCenter}
            nozzleDiameter={0.4}
            extruderColors={extruderColors}
          />
        )}
      </div>
    </div>
  );
}

const statusEl = document.getElementById('status');
if (statusEl) statusEl.remove();

const root = createRoot(document.getElementById('root')!);
root.render(<TestApp />);
