// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * End-to-end pipeline test: config building -> GCode parsing -> stats extraction.
 *
 * Since the OrcaSlicer WASM binary requires a browser/worker context (fetch,
 * Blob, SharedArrayBuffer), this test validates the complete pipeline EXCEPT
 * the actual WASM slicing step by using hardcoded OrcaSlicer-format GCode
 * output for a 10mm cube.
 *
 * Tests:
 * 1. buildOrcaConfig() produces valid config from default settings
 * 2. WASM artifacts exist on disk (file presence check)
 * 3. parseGCode() correctly parses realistic OrcaSlicer output for a 10mm cube
 * 4. parseGcodeStats() extracts print time and filament usage
 * 5. GCode preview data (layers, segments, bounds) is correct for the sliced cube
 *
 * For actual WASM load + slice tests, use the Playwright integration tests
 * (`npm run test:integration`) which run in a real browser context.
 */

import { describe, it, expect } from 'vitest';
import { existsSync } from 'fs';
import { resolve } from 'path';
import { buildOrcaConfig, type PrinterSettings } from '../orca-slicer-settings';
import { DEFAULT_PRINT_PROFILE } from '../../types/print-profile';
import type { ResolvedFilamentSettings } from '../../hooks/usePrinterFilamentOverrides';
import { parseGCode, type ParsedGCode, type MoveType } from '../gcode-parser';
import { parseGcodeStats } from '../../hooks/useSlicer';

// ─── Test fixtures ───────────────────────────────────────

const PLA_FILAMENT: ResolvedFilamentSettings = {
  nozzleTemp: 210,
  bedTemp: 60,
  fanSpeed: 100,
  firstLayerFan: 0,
  printSpeed: 50,
  retractDist: 4,
  retractSpeed: 45,
  deretractionSpeed: 0,
  firstLayerNozzleTemp: 215,
  firstLayerBedTemp: 65,
  minSpeed: 20,
  minLayerTime: 6,
  flowRatio: 1.0,
  enablePressureAdvance: false,
  pressureAdvance: 0.04,
  adaptivePressureAdvance: false,
  overhangFanSpeed: 100,
  overhangFanThreshold: 0,
  enableOverhangBridgeFan: true,
  closeFanFirstLayers: 1,
  fanCoolingLayerTime: 60,
  slowDownLayerTime: 4,
  fanMaxSpeed: 100,
  coolPlateTemp: 60,
  coolPlateTempInitialLayer: 65,
  engPlateTemp: 60,
  engPlateTempInitialLayer: 65,
  texturedPlateTemp: 60,
  texturedPlateTempInitialLayer: 65,
};

const ENDER3_PRINTER: PrinterSettings = {
  bedWidth: 235,
  bedDepth: 235,
  maxHeight: 250,
  originCenter: false,
  startGcode: 'G28\nG29\nM109 S{first_layer_temperature[0]}\nM190 S{first_layer_bed_temperature[0]}',
  endGcode: 'M104 S0\nM140 S0\nG28 X Y\nM84',
  toolChangeGcode: '',
  printableArea: [],
  bedExcludeAreas: [],
  printerStructureType: 'i3',
  nozzleType: 'brass',
  nozzleHRC: 0,
  auxiliaryFan: false,
  chamberTempControl: false,
  maxVolumetricSpeed: 0,
};

/**
 * Realistic OrcaSlicer GCode for a 10mm cube at 0.2mm layer height.
 * OrcaSlicer uses the same ;TYPE: / ;LAYER_CHANGE / ;Z: comment format
 * as PrusaSlicer (since both share the libslic3r lineage), so the
 * existing gcode-parser handles it without changes.
 *
 * The cube sits at the center of a 235x235 bed (117.5, 117.5).
 * 50 layers at 0.2mm = 10mm total height (first layer at 0.3mm, then 0.2mm).
 * Simplified to 3 representative layers for test brevity.
 */
const ORCASLICER_10MM_CUBE_GCODE = `; generated by OrcaSlicer 2.3.1 on 2026-03-14 at 10:00:00 UTC
; outer wall extrusion width = 0.40mm
; inner wall extrusion width = 0.45mm
; sparse infill extrusion width = 0.45mm
; internal solid infill extrusion width = 0.45mm
; top surface extrusion width = 0.40mm
G90 ; use absolute coordinates
M83 ; extruder relative mode
G28 ; home all axes
G29 ; mesh bed leveling
M109 S215 ; wait for nozzle temp
M190 S65 ; wait for bed temp
G92 E0 ; reset extruder
;LAYER_CHANGE
;Z:0.3
;HEIGHT:0.3
;TYPE:Skirt/Brim
G1 Z0.3 F7200
G1 X109.5 Y109.5 F10800
G1 X109.5 Y125.5 E0.6272 F1500
G1 X125.5 Y125.5 E0.6272
G1 X125.5 Y109.5 E0.6272
G1 X109.6 Y109.5 E0.6234
;TYPE:External perimeter
G1 X112.5 Y112.5 F10800
G1 X112.5 Y122.5 E0.3920 F1080
G1 X122.5 Y122.5 E0.3920
G1 X122.5 Y112.5 E0.3920
G1 X112.6 Y112.5 E0.3881
;TYPE:Perimeter
G1 X112.95 Y112.95 F10800
G1 X112.95 Y122.05 E0.3568 F1500
G1 X122.05 Y122.05 E0.3568
G1 X122.05 Y112.95 E0.3568
G1 X113.05 Y112.95 E0.3529
;TYPE:Solid infill
G1 X113.4 Y113.4 F10800
G1 X121.6 Y113.4 E0.3216 F1500
G1 X113.4 Y113.85 F10800
G1 X121.6 Y113.85 E0.3216
G1 X113.4 Y114.3 F10800
G1 X121.6 Y114.3 E0.3216
G1 X113.4 Y114.75 F10800
G1 X121.6 Y114.75 E0.3216
G1 X113.4 Y115.2 F10800
G1 X121.6 Y115.2 E0.3216
G1 X113.4 Y115.65 F10800
G1 X121.6 Y115.65 E0.3216
G1 X113.4 Y116.1 F10800
G1 X121.6 Y116.1 E0.3216
G1 X113.4 Y116.55 F10800
G1 X121.6 Y116.55 E0.3216
G1 X113.4 Y117.0 F10800
G1 X121.6 Y117.0 E0.3216
G1 X113.4 Y117.45 F10800
G1 X121.6 Y117.45 E0.3216
G1 X113.4 Y117.9 F10800
G1 X121.6 Y117.9 E0.3216
G1 X113.4 Y118.35 F10800
G1 X121.6 Y118.35 E0.3216
G1 X113.4 Y118.8 F10800
G1 X121.6 Y118.8 E0.3216
G1 X113.4 Y119.25 F10800
G1 X121.6 Y119.25 E0.3216
G1 X113.4 Y119.7 F10800
G1 X121.6 Y119.7 E0.3216
G1 X113.4 Y120.15 F10800
G1 X121.6 Y120.15 E0.3216
G1 X113.4 Y120.6 F10800
G1 X121.6 Y120.6 E0.3216
G1 X113.4 Y121.05 F10800
G1 X121.6 Y121.05 E0.3216
G1 X113.4 Y121.5 F10800
G1 X121.6 Y121.5 E0.3216
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.2
;TYPE:External perimeter
G1 X112.5 Y112.5 Z0.5 F10800
G1 X112.5 Y122.5 E0.3920 F1080
G1 X122.5 Y122.5 E0.3920
G1 X122.5 Y112.5 E0.3920
G1 X112.6 Y112.5 E0.3881
;TYPE:Perimeter
G1 X112.95 Y112.95 F10800
G1 X112.95 Y122.05 E0.3568 F1500
G1 X122.05 Y122.05 E0.3568
G1 X122.05 Y112.95 E0.3568
G1 X113.05 Y112.95 E0.3529
;TYPE:Internal infill
G1 X113.4 Y113.4 F10800
G1 X121.6 Y121.6 E0.4640 F1500
G1 X113.4 Y114.3 F10800
G1 X120.7 Y121.6 E0.4128
;LAYER_CHANGE
;Z:10.1
;HEIGHT:0.2
;TYPE:External perimeter
G1 X112.5 Y112.5 Z10.1 F10800
G1 X112.5 Y122.5 E0.3920 F1080
G1 X122.5 Y122.5 E0.3920
G1 X122.5 Y112.5 E0.3920
G1 X112.6 Y112.5 E0.3881
;TYPE:Perimeter
G1 X112.95 Y112.95 F10800
G1 X112.95 Y122.05 E0.3568 F1500
G1 X122.05 Y122.05 E0.3568
G1 X122.05 Y112.95 E0.3568
G1 X113.05 Y112.95 E0.3529
;TYPE:Top solid infill
G1 X113.4 Y113.4 F10800
G1 X121.6 Y113.4 E0.3216 F750
G1 X113.4 Y113.85 F10800
G1 X121.6 Y113.85 E0.3216
G1 X113.4 Y114.3 F10800
G1 X121.6 Y114.3 E0.3216
G1 X113.4 Y114.75 F10800
G1 X121.6 Y114.75 E0.3216
G1 X113.4 Y115.2 F10800
G1 X121.6 Y115.2 E0.3216
G1 X113.4 Y115.65 F10800
G1 X121.6 Y115.65 E0.3216
G1 X113.4 Y116.1 F10800
G1 X121.6 Y116.1 E0.3216
G1 X113.4 Y116.55 F10800
G1 X121.6 Y116.55 E0.3216
G1 X113.4 Y117.0 F10800
G1 X121.6 Y117.0 E0.3216
G1 X113.4 Y117.45 F10800
G1 X121.6 Y117.45 E0.3216
G1 X113.4 Y117.9 F10800
G1 X121.6 Y117.9 E0.3216
G1 X113.4 Y118.35 F10800
G1 X121.6 Y118.35 E0.3216
G1 X113.4 Y118.8 F10800
G1 X121.6 Y118.8 E0.3216
G1 X113.4 Y119.25 F10800
G1 X121.6 Y119.25 E0.3216
G1 X113.4 Y119.7 F10800
G1 X121.6 Y119.7 E0.3216
G1 X113.4 Y120.15 F10800
G1 X121.6 Y120.15 E0.3216
G1 X113.4 Y120.6 F10800
G1 X121.6 Y120.6 E0.3216
G1 X113.4 Y121.05 F10800
G1 X121.6 Y121.05 E0.3216
G1 X113.4 Y121.5 F10800
G1 X121.6 Y121.5 E0.3216
M104 S0 ; turn off nozzle heater
M140 S0 ; turn off bed heater
G28 X Y ; home X and Y
M84 ; disable motors
; filament used [mm] = 4823.7
; filament used [cm3] = 11.61
; filament used [g] = 14.52
; filament cost = 0.23
; estimated printing time (normal mode) = 0h 47m 12s
; estimated printing time (silent mode) = 1h 2m 30s
`;

// ─── Test Suite ──────────────────────────────────────────

describe('E2E Pipeline: config -> gcode parse -> stats', () => {

  // ── Step 1: Config building ────────────────────────────

  describe('Step 1: buildOrcaConfig with default 10mm cube settings', () => {
    const config = buildOrcaConfig(
      DEFAULT_PRINT_PROFILE,
      PLA_FILAMENT,
      ENDER3_PRINTER,
      null,
      1,
    );

    it('produces non-empty config', () => {
      expect(Object.keys(config).length).toBeGreaterThan(50);
    });

    it('has correct layer height for default profile', () => {
      expect(config['layer_height']).toBe('0.2');
      expect(config['initial_layer_print_height']).toBe('0.3');
    });

    it('has correct temperature from PLA filament', () => {
      expect(config['nozzle_temperature']).toBe('210');
      expect(config['hot_plate_temp']).toBe('60');
      expect(config['nozzle_temperature_initial_layer']).toBe('215');
      expect(config['hot_plate_temp_initial_layer']).toBe('65');
    });

    it('has correct printable area for Ender 3', () => {
      expect(config['printable_area']).toBe('0x0;235x0;235x235;0x235');
    });

    it('has correct nozzle and filament diameter', () => {
      expect(config['nozzle_diameter']).toBe('0.4');
      expect(config['filament_diameter']).toBe('1.75');
    });

    it('has start/end gcode passed through', () => {
      // Non-Klipper expressions like {first_layer_temperature[0]} pass through unchanged
      expect(config['machine_start_gcode']).toContain('{first_layer_temperature[0]}');
      expect(config['machine_end_gcode']).toBe('M104 S0\nM140 S0\nG28 X Y\nM84');
    });

    it('has correct infill settings', () => {
      expect(config['sparse_infill_density']).toBe('15%');
      expect(config['sparse_infill_pattern']).toBe('gyroid');
      expect(config['infill_direction']).toBe('45');
    });

    it('has correct speed settings', () => {
      expect(config['outer_wall_speed']).toBe('120');
      expect(config['sparse_infill_speed']).toBe('200');
      expect(config['bridge_speed']).toBe('25');
      expect(config['travel_speed']).toBe('300');
    });

    it('has correct retraction settings', () => {
      expect(config['retraction_length']).toBe('4');
      expect(config['retraction_speed']).toBe('45');
      expect(config['retract_when_changing_layer']).toBe('1');
    });

    it('has correct adhesion settings (skirt)', () => {
      expect(config['skirt_loops']).toBe('3');
      expect(config['brim_width']).toBe('0');
      expect(config['raft_layers']).toBe('0');
    });

    it('has correct fan settings', () => {
      expect(config['fan_max_speed']).toBe('100');
      expect(config['fan_min_speed']).toBe('100');
      expect(config['close_fan_the_first_x_layers']).toBe('1');
    });

    it('has OrcaSlicer-specific config keys (not PrusaSlicer)', () => {
      // These keys exist only in OrcaSlicer, not PrusaSlicer
      expect(config['wall_loops']).toBeDefined();
      expect(config['sparse_infill_density']).toBeDefined();
      expect(config['initial_layer_print_height']).toBeDefined();
      expect(config['enable_support']).toBeDefined();
      expect(config['machine_start_gcode']).toBeDefined();

      // PrusaSlicer key names should NOT appear
      expect(config['perimeters']).toBeUndefined();
      expect(config['fill_density']).toBeUndefined();
      expect(config['first_layer_height']).toBeUndefined();
      expect(config['support_material']).toBeUndefined();
      expect(config['start_gcode']).toBeUndefined();
      expect(config['bed_shape']).toBeUndefined();
      expect(config['bed_temperature']).toBeUndefined();
      expect(config['temperature']).toBeUndefined();
    });

    it('has OrcaSlicer-only features in config', () => {
      // Wall sequence (OrcaSlicer enum, PrusaSlicer uses external_perimeters_first bool)
      expect(config['wall_sequence']).toBeDefined();
      // Scarf joint seam (OrcaSlicer only)
      expect(config['seam_slope_type']).toBeDefined();
      // Printable area (OrcaSlicer uses polygon, PrusaSlicer uses bed_shape)
      expect(config['printable_area']).toBeDefined();
    });
  });

  // ── Step 2: WASM artifacts ─────────────────────────────

  describe('Step 2: OrcaSlicer WASM artifacts exist', () => {
    const wasmDir = resolve(__dirname, '../../../public/wasm');

    it('libslic3r.js exists', () => {
      expect(existsSync(resolve(wasmDir, 'libslic3r.js'))).toBe(true);
    });

    it('libslic3r.wasm exists', () => {
      expect(existsSync(resolve(wasmDir, 'libslic3r.wasm'))).toBe(true);
    });

    it('libslic3r.wasm is a reasonable size (> 1MB)', () => {
      const { statSync } = require('fs');
      const stat = statSync(resolve(wasmDir, 'libslic3r.wasm'));
      // OrcaSlicer WASM should be ~9-15MB
      expect(stat.size).toBeGreaterThan(1_000_000);
    });
  });

  // ── Step 3: GCode parsing ─────────────────────────────

  describe('Step 3: parseGCode on OrcaSlicer 10mm cube output', () => {
    let parsed: ParsedGCode;

    // Parse once for all sub-tests
    parsed = parseGCode(ORCASLICER_10MM_CUBE_GCODE);

    it('detects 3 layers', () => {
      expect(parsed.layers).toHaveLength(3);
    });

    it('has correct Z heights for each layer', () => {
      expect(parsed.layers[0].z).toBeCloseTo(0.3, 2);
      expect(parsed.layers[1].z).toBeCloseTo(0.5, 2);
      expect(parsed.layers[2].z).toBeCloseTo(10.1, 2);
    });

    it('has sequential layer indices', () => {
      expect(parsed.layers[0].layerIndex).toBe(0);
      expect(parsed.layers[1].layerIndex).toBe(1);
      expect(parsed.layers[2].layerIndex).toBe(2);
    });

    it('has non-zero total segment count', () => {
      expect(parsed.totalSegments).toBeGreaterThan(10);
    });

    it('has reasonable bounds for cube centered on 235x235 bed', () => {
      // Cube perimeters go from ~112.5 to ~122.5
      expect(parsed.bounds.minX).toBeLessThanOrEqual(113);
      expect(parsed.bounds.maxX).toBeGreaterThanOrEqual(121);
      expect(parsed.bounds.minY).toBeLessThanOrEqual(113);
      expect(parsed.bounds.maxY).toBeGreaterThanOrEqual(121);
      // Z range: 0.3 to 10.1
      expect(parsed.bounds.minZ).toBeLessThanOrEqual(0.5);
      expect(parsed.bounds.maxZ).toBeGreaterThanOrEqual(10);
    });

    it('detects skirt/brim on first layer only', () => {
      const layer0Types = new Set(parsed.layers[0].segments.map(s => s.type));
      const layer1Types = new Set(parsed.layers[1].segments.map(s => s.type));
      const layer2Types = new Set(parsed.layers[2].segments.map(s => s.type));
      expect(layer0Types.has('brim')).toBe(true); // Skirt/Brim maps to 'brim'
      expect(layer1Types.has('brim')).toBe(false);
      expect(layer2Types.has('brim')).toBe(false);
    });

    it('detects wall segments (External perimeter + Perimeter)', () => {
      const wallSegments = parsed.layers.flatMap(l =>
        l.segments.filter(s => s.type === 'wall')
      );
      expect(wallSegments.length).toBeGreaterThan(0);
      // Walls should appear on every layer
      for (const layer of parsed.layers) {
        const hasWalls = layer.segments.some(s => s.type === 'wall');
        expect(hasWalls).toBe(true);
      }
    });

    it('detects solid infill on first layer (bottom)', () => {
      const layer0 = parsed.layers[0];
      const hasSolidFill = layer0.segments.some(s => s.type === 'solid-fill');
      expect(hasSolidFill).toBe(true);
    });

    it('detects internal infill on middle layer', () => {
      const layer1 = parsed.layers[1];
      const hasInfill = layer1.segments.some(s => s.type === 'infill');
      expect(hasInfill).toBe(true);
    });

    it('detects top solid infill on last layer', () => {
      const lastLayer = parsed.layers[parsed.layers.length - 1];
      const hasSolidFill = lastLayer.segments.some(s => s.type === 'solid-fill');
      expect(hasSolidFill).toBe(true);
    });

    it('all extrusion segments have extruder 0 (single color)', () => {
      for (const layer of parsed.layers) {
        for (const seg of layer.segments) {
          if (seg.type !== 'travel') {
            expect(seg.extruder).toBe(0);
          }
        }
      }
    });

    it('travel moves exist (non-extruding repositioning)', () => {
      const travelSegments = parsed.layers.flatMap(l =>
        l.segments.filter(s => s.type === 'travel')
      );
      expect(travelSegments.length).toBeGreaterThan(0);
    });

    it('has the expected feature type distribution', () => {
      const typeCounts = new Map<MoveType, number>();
      for (const layer of parsed.layers) {
        for (const seg of layer.segments) {
          typeCounts.set(seg.type, (typeCounts.get(seg.type) ?? 0) + 1);
        }
      }
      // The cube should have walls, solid fill, infill, brim, and travel
      expect(typeCounts.has('wall')).toBe(true);
      expect(typeCounts.has('solid-fill')).toBe(true);
      expect(typeCounts.has('infill')).toBe(true);
      expect(typeCounts.has('brim')).toBe(true);
      expect(typeCounts.has('travel')).toBe(true);

      // Walls should be the dominant extrusion type (perimeters on every layer)
      const wallCount = typeCounts.get('wall') ?? 0;
      expect(wallCount).toBeGreaterThan(5);
    });

    it('OrcaSlicer ;TYPE: comments are correctly parsed (same format as PrusaSlicer)', () => {
      // OrcaSlicer uses identical ;TYPE: comment format to PrusaSlicer
      // since both derive from libslic3r. Verify all expected types are detected.
      const allTypes = new Set<MoveType>();
      for (const layer of parsed.layers) {
        for (const seg of layer.segments) {
          allTypes.add(seg.type);
        }
      }
      // Our fixture includes these ;TYPE: comments:
      // Skirt/Brim, External perimeter, Perimeter, Solid infill,
      // Internal infill, Top solid infill
      expect(allTypes.has('brim')).toBe(true);        // ;TYPE:Skirt/Brim
      expect(allTypes.has('wall')).toBe(true);         // ;TYPE:External perimeter, ;TYPE:Perimeter
      expect(allTypes.has('solid-fill')).toBe(true);   // ;TYPE:Solid infill, ;TYPE:Top solid infill
      expect(allTypes.has('infill')).toBe(true);       // ;TYPE:Internal infill
      expect(allTypes.has('travel')).toBe(true);       // Non-extruding moves
    });
  });

  // ── Step 4: Stats extraction ──────────────────────────

  describe('Step 4: parseGcodeStats extracts print time and filament', () => {
    it('extracts print time in seconds (47m 12s = 2832s)', () => {
      const stats = parseGcodeStats(ORCASLICER_10MM_CUBE_GCODE);
      expect(stats.printTime).toBe(47 * 60 + 12);
    });

    it('extracts filament used in mm', () => {
      const stats = parseGcodeStats(ORCASLICER_10MM_CUBE_GCODE);
      expect(stats.filamentUsed).toBeCloseTo(4823.7, 1);
    });

    it('returns both stats together', () => {
      const stats = parseGcodeStats(ORCASLICER_10MM_CUBE_GCODE);
      expect(stats.printTime).toBeDefined();
      expect(stats.filamentUsed).toBeDefined();
      expect(stats.printTime).toBeGreaterThan(0);
      expect(stats.filamentUsed!).toBeGreaterThan(0);
    });

    it('OrcaSlicer uses same stats comment format as PrusaSlicer', () => {
      // Both use: "; estimated printing time (normal mode) = ..."
      // Both use: "; filament used [mm] = ..."
      // This is because both share the libslic3r GCode export code
      const stats = parseGcodeStats(ORCASLICER_10MM_CUBE_GCODE);
      expect(stats.printTime).toBe(2832);
      expect(stats.filamentUsed).toBeCloseTo(4823.7, 1);
    });
  });

  // ── Step 5: Full pipeline coherence ───────────────────

  describe('Step 5: pipeline coherence checks', () => {
    it('config layer_height matches GCode layer spacing', () => {
      const config = buildOrcaConfig(DEFAULT_PRINT_PROFILE, PLA_FILAMENT, ENDER3_PRINTER, null, 1);
      const parsed = parseGCode(ORCASLICER_10MM_CUBE_GCODE);

      // First layer height from config should match first layer Z
      expect(parseFloat(config['initial_layer_print_height'])).toBeCloseTo(parsed.layers[0].z, 1);

      // Second layer Z should be initial_layer_print_height + layer_height
      const expectedSecondLayerZ = parseFloat(config['initial_layer_print_height'])
        + parseFloat(config['layer_height']);
      expect(parsed.layers[1].z).toBeCloseTo(expectedSecondLayerZ, 1);
    });

    it('parsed bounds are within configured bed size', () => {
      const parsed = parseGCode(ORCASLICER_10MM_CUBE_GCODE);

      // printable_area = 0x0;235x0;235x235;0x235 means X: 0-235, Y: 0-235
      expect(parsed.bounds.minX).toBeGreaterThanOrEqual(0);
      expect(parsed.bounds.maxX).toBeLessThanOrEqual(235);
      expect(parsed.bounds.minY).toBeGreaterThanOrEqual(0);
      expect(parsed.bounds.maxY).toBeLessThanOrEqual(235);
    });

    it('filament used is reasonable for a 10mm cube', () => {
      const stats = parseGcodeStats(ORCASLICER_10MM_CUBE_GCODE);
      // A 10mm cube at 20% infill typically uses 2000-8000mm of 1.75mm filament
      expect(stats.filamentUsed).toBeGreaterThan(1000);
      expect(stats.filamentUsed).toBeLessThan(15000);
    });

    it('print time is reasonable for a 10mm cube', () => {
      const stats = parseGcodeStats(ORCASLICER_10MM_CUBE_GCODE);
      // A 10mm cube typically takes 15-90 minutes
      expect(stats.printTime).toBeGreaterThan(15 * 60); // > 15 minutes
      expect(stats.printTime).toBeLessThan(90 * 60);    // < 90 minutes
    });

    it('GCode preview has enough segments per layer for visualization', () => {
      const parsed = parseGCode(ORCASLICER_10MM_CUBE_GCODE);
      for (const layer of parsed.layers) {
        // Each layer should have at least a few extrusion segments
        const extrusionSegments = layer.segments.filter(s => s.type !== 'travel');
        expect(extrusionSegments.length).toBeGreaterThan(2);
      }
    });

    it('GCode preview layers are sorted by Z height', () => {
      const parsed = parseGCode(ORCASLICER_10MM_CUBE_GCODE);
      for (let i = 1; i < parsed.layers.length; i++) {
        expect(parsed.layers[i].z).toBeGreaterThan(parsed.layers[i - 1].z);
      }
    });

    it('config produces OrcaSlicer keys not PrusaSlicer keys', () => {
      const config = buildOrcaConfig(DEFAULT_PRINT_PROFILE, PLA_FILAMENT, ENDER3_PRINTER, null, 1);

      // Spot-check key naming is OrcaSlicer convention
      const keys = Object.keys(config);
      expect(keys).toContain('wall_loops');
      expect(keys).toContain('sparse_infill_density');
      expect(keys).toContain('hot_plate_temp');
      expect(keys).toContain('nozzle_temperature');
      expect(keys).toContain('printable_area');
      expect(keys).toContain('machine_start_gcode');
      expect(keys).toContain('retraction_length');

      // Must NOT contain PrusaSlicer key names
      expect(keys).not.toContain('perimeters');
      expect(keys).not.toContain('fill_density');
      expect(keys).not.toContain('bed_temperature');
      expect(keys).not.toContain('temperature');
      expect(keys).not.toContain('bed_shape');
      expect(keys).not.toContain('start_gcode');
      expect(keys).not.toContain('retract_length');
    });

    it('multi-extruder config uses OrcaSlicer comma separator for numeric arrays', () => {
      const config = buildOrcaConfig(DEFAULT_PRINT_PROFILE, PLA_FILAMENT, ENDER3_PRINTER, null, 2);

      // OrcaSlicer uses ',' for per-extruder numeric values (ConfigOptionFloats/Ints)
      expect(config['nozzle_temperature']).toBe('210,210');
      expect(config['retraction_length']).toBe('4,4');
      expect(config['nozzle_diameter']).toBe('0.4,0.4');
    });
  });
});
